labs/api/urls.py
from django.urls import path
from .solrapi import (
    JudaicalinkProxy, CMProxy,
    CMEntitiesProxy, CMEntityNamesProxy, CMMetaProxy
)
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# API endpoints
urlpatterns = [
    path('judaicalink/',        JudaicalinkProxy.as_view(),    name='api-jl'),
    path('cm/',                 CMProxy.as_view(),             name='api-cm'),
    path('cm/entities/',        CMEntitiesProxy.as_view(),      name='api-cm-entities'),
    path('cm/names/',           CMEntityNamesProxy.as_view(),   name='api-cm-entity-names'),
    path('cm/meta/',            CMMetaProxy.as_view(),          name='api-cm-meta'),
]

# Swagger / ReDoc
schema_view = get_schema_view(
    openapi.Info(
        title="Judaicalink Search API",
        default_version='v1',
        description="Solr‐backed search endpoints",
        contact=openapi.Contact(email="info@judaicalink.org"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='api-swagger'),
    path('redoc/',   schema_view.with_ui('redoc',   cache_timeout=0), name='api-redoc'),
]

labs/cm_e_search/urls.py
from django.urls import path
# for the sitemap
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

from . import views
sitemaps = {'static': StaticViewSitemap}

app_name = 'cm_e_search'

urlpatterns = [
    path('', views.index, name='entity_search_index'),
    path('search_result/', views.result, name='search_result'),
    path('get-names', views.get_names_json, name='get_names'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

labs/labs/urls.py
from django.contrib import admin
from django.urls import include, path

from search import views as search_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search.urls', namespace='search')),
    path('', search_views.index, name='index'),
    path('cm_search/', include('cm_search.urls')),
    path('cm_e_search/', include('cm_e_search.urls')),
    path('data/', include('data.urls')),
    #path('captcha/', include('captcha.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


#urlpatterns += [
#    path('captcha/', include('captcha.urls')),
#    ]

handler404 = 'search.views.error_404'
handler500 = 'search.views.error_500'
handler403 = 'search.views.error_403'
handler400 = 'search.views.error_400'

labs/search/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .sitemaps import StaticViewSitemap

# for the sitemap
from django.contrib.sitemaps.views import sitemap

from . import views

sitemaps = {'static': StaticViewSitemap}

app_name = 'search'

urlpatterns = [
    path('index', views.index, name='index'),
    path('all_search_nav', views.all_search_nav, name='all_search_nav'),
    path('search', views.search, name='search'),
    # the sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

labs/cm_e_search/models.py
from django.db import models

# Create your models here.

labs/search/forms.py
"""
This pages generates the forms for the search.
The forms are generated with crispy forms.
Benjamin Schnabel, 2024
b.schnabel@hs-mannheim.de
"""

from crispy_forms.helper import FormHelper
from django import forms


class SearchForm(forms.Form):
    pass

labs/cm_e_search/views.py
import logging
import html
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import pysolr
import math, json, pprint
from django.conf import settings
from django.views.decorators.cache import cache_page
from django.core.cache.backends.base import DEFAULT_TIMEOUT

logger = logging.getLogger('labs')
logger.setLevel(logging.DEBUG)
CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)
SOLR_SERVER = settings.SOLR_SERVER


def get_names():
    """
    This function gets all the names from the solr index cm_entity_names
    :return: list of names
    """
    # gets all entity names from solr
    try:
        names = []

        solr = pysolr.Solr(SOLR_SERVER + "cm_entity_names", always_commit=True, timeout=10,
                           auth=(settings.SOLR_USER, settings.SOLR_PASSWORD))
        res = solr.search('*:*', index="cm_entity_names", rows=10000)

        # logging
        logger.debug("Got names from solr: ")
        logger.debug("Names found: %s", res.hits)
        logger.debug(res.hits)

        for doc in res.docs:
            # convert list to string
            doc['name'] = ''.join(map(str, doc['name']))
            names.append(html.escape(doc['name']).replace("'", "\\'").replace('"', '\\"'))
            #logger.debug("Doc: %s", doc['name'])
        # sort names alphabetically
        names.sort()
        return names

    except Exception as e:
        logger.error("Error: %s", e)
        return None

    except pysolr.SolrError as e:
        logger.error("Error: %s", e)
        return None


#@cache_page(CACHE_TTL)
def index(request):
    context = {'names': get_names()}
    return render(request, 'cm_e_search/search_index.html', context)


#@cache_page(CACHE_TTL)
def result(request):
    names = get_names()

    query = request.GET.get('query', '')  # Safely get the query with a default value

    try:
        solr = pysolr.Solr(SOLR_SERVER + 'cm_entities', always_commit=True, timeout=10,
                           auth=(settings.SOLR_USER, settings.SOLR_PASSWORD))

        fields = ["name", "e_type", "related_entities", 'ep', 'id', 'journal_occs.j_name', 'journal_occs.j_id',
                  'journal_occs.first', 'journal_occs.last', 'journal_occs.mentions.p_id',
                  'journal_occs.mentions.spot', 'journal_occs.mentions.start', 'journal_occs.mentions.end',
                  'journal_occs.mentions.p_link', 'journal_occs.mentions.date', 'journal_occs.mentions.year']

        search_fields = ["name", "spot"]

        # Safely build the query list
        solr_query = [field + ':"' + (query or '') + '"' for field in search_fields]

        # Build Solr search body
        body = {
            "hl": "false",
            "indent": "true",
            'fl': '*,[child ]',
            "start": 0,
            "q.op": "OR",
            "rows": 1000,
            "useParams": ""
        }

        res = solr.search(q=solr_query, search_handler="/select", **body)

    except pysolr.SolrError as e:
        logger.error("Error: %s", e)
        res.docs = []


    results = []
    for doc in res.docs:
        doc['name'] = ''.join(map(str, doc.get('name', '')))
        doc['e_type'] = ''.join(map(str, doc.get('e_type', '')))
        doc['ep'] = ''.join(map(str, doc.get('ep', ''))) if 'ep' in doc else ''

        related_entities = []
        if 'related_entities' in doc:
            for index in range(0, len(doc['related_entities']), 4):
                if index + 3 < len(doc['related_entities']):
                    entity = {
                        'ep': doc['related_entities'][index] or '',
                        'name': doc['related_entities'][index + 1] or '',
                        'score': doc['related_entities'][index + 2] or '',
                        'type': doc['related_entities'][index + 3] or '',
                    }
                    related_entities.append(entity)
        doc['related_entities'] = related_entities

        results.append(doc)
        
    """
    Occurs in journals
    Todo get the nested documents for:
    * docs
        * name
        * entity_type: String
        * entity_page: String (URL)
        * journal_occurrences (nested, multiple)
            * journal_name: String
            * journal_id: Int
            * first: Int
            * last: Int
            * mentions (nested, multiple)
                * person_id: Int
                * spot: String
                * start: Int
                * end: Int
                * person_link: String 
                * date: String or Date
                * year: Int
        * related_entities (nested, multiple)
            * name: String
            * url: String
            * score: Float
            * type: String
    """

    context = {
        "results": results,
        "names": names,
        "error_message": "",
    }

    return render(request, 'cm_e_search/search_result.html', context)



def get_names_json(request):
    names = get_names()
    logger.debug("Names: %s", names)
    return JsonResponse({'names': names})


def create_map(result):
    # creates a map from locations
    locations = []
    for r in result:
        if r.e_type == 'LOC':
            locations.append(r.name)
    pass


def create_timeline():
    pass


def create_graph_visualization():
    pass

from django.core.paginator import Paginator

#@cache_page(CACHE_TTL)
def names_by_letter(request, letter):
    names = get_names()  # Fetch all names
    filtered_names = [name for name in names if name.startswith(letter.upper())]

    # Paginate the filtered names
    paginator = Paginator(filtered_names, 50)  # 50 names per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'letter': letter.upper(), 
        'page_obj': page_obj,
    }
    return render(request, 'cm_e_search/names_by_letter.html', context)

labs/cm_e_search/templates/cm_e_search/search_form.html
<!-- search_form.html -->
<form method="get" action="{% url 'cm_e_search:search_result' %}" class="row g-0">
    <div class="col-lg-10 col-auto form-group" id="autocomplete-search"></div>
</form>

labs/cm_e_search/templates/cm_e_search/search_index.html
{% extends 'search/base.html' %}
{% load static %}


{% block meta %}
<meta name="keywords" content="judaicalink, search, entity search, compact memory, access">
<meta name="description"
      content="Through this interface the user can search persons and places automatically extracted from Compact Memory and linked to Judaicalink entries.">
{% endblock %}


{% block content %}
<!--content-->
<main class="row">

    <div class="col-12 col-sm-12 ml-xl-0 col-md-12 col-lg-9 col-xl-8">
        <div class="row">
            <h1 class="text-center">Compact Memory Entity Search</h1>
        </div>

        {% include "cm_e_search/search_form.html" %}

        <div class="row">
            <p>The Compact Memory collection comprises over 300 Jewish newspapers and journals of the German speaking
                area of the years 1768–1938 and beyond.
                <br>Through this interface the user can search <b>persons</b> and <b>places</b> automatically extracted
                from Compact Memory and <b>linked to Judaicalink entries</b>.
            </p>
        </div>
    </div>

    <div class="col-md-0 col-lg-3 col-xl-4">
        <div class="alert alert-info text-center mt-4 sticky-top" id="picturemargintop30" role="alert">
            <b>Try some search keywords:</b>
            <ul class="list-unstyled">
                <li><i class="fa fa-search-plus"></i> <a
                        href="{% url 'cm_e_search:search_result' %}?query=Albert+Einstein">Albert Einstein</a></li>
                <li><i class="fa fa-search-plus"></i> <a
                        href="{% url 'cm_e_search:search_result' %}?query=Berlin">Berlin</a>
                </li>
                <li><i class="fa fa-search-plus"></i> <a
                        href="{% url 'cm_e_search:search_result' %}?query=Theodor+Herzl">Theodor Herzl</a></li>
                <li><i class="fa fa-search-plus"></i> <a
                        href="{% url 'cm_e_search:search_result' %}?query=Gershom+Scholem">Gershom Scholem</a></li>
            </ul>
        </div>
    </div>

</main>
<!--content end-->

{% endblock content %}

labs/cm_e_search/templates/cm_e_search/search_result.html
{% extends 'search/base.html' %}
{% load static %}

{% block header_scripts %}
<script>
    function more_items(classname) {

        var tail_items = document.getElementsByClassName(classname);
        var btn = document.getElementById("more_e");

        var i = 0;
        for (const item of tail_items) {
            if (item.style.display === "none") {
                item.style.display = "list-item";
                i++;
            }
            if (i > 9) {
                break;
            }
        }
        if (document.getElementById("less_e").style.display === "none") {
            document.getElementById("less_e").style.display = "block";
        }
    }

    function less_items(classname) {

        var tail_items = document.getElementsByClassName(classname);
        var btn = document.getElementById("less_e");

        var j = 0
        for (var i = tail_items.length - 1; i >= 10; i--) {

            if (tail_items[i].style.display === "list-item") {
                tail_items[i].style.display = "none";
                j++;
            }
            if (j > 9) {
                break;
            }

        }
    }

    function show_journal(counter) {

        var div = document.getElementById(counter);

        if (div.style.display === "none") {

            div.style.display = "block";
        } else {
            div.style.display = "none";
        }
    }
</script>

{% endblock header_scripts %}

{% block content %}
<main class="row">

    <div class="col-12 col-sm-12 ml-xl-0 col-md-12 col-lg-9 col-xl-8">
        <div class="row">
            <h1 class="text-center">Compact Memory Entity Search</h1>
        </div>

        {% include "cm_e_search/search_form.html" %}

        {% if error_message %}
        <div class="alert alert-danger text-center mb-5" role="alert">
            {{ error_message }}
        </div>
        {% endif %}

        <div>


            {% for result in results %}

            <div class="alert alert-success text-center" role="alert">
                {% if result.e_type == 'PER' %}
                <b>Name</b>: {{ result.name }} <span class="badge rounded-pill text-white bg-primary">person</span>
                {% elif result.e_type == 'LOC' %}
                <b>Name</b>: {{ result.name }} <span class="badge rounded-pill text-white bg-info">location</span>
                {% else %}
                <p><b>Name</b>: {{ result.name }} <span class="badge rounded-pill text-white bg-dark">other</span>
                    {% endif %}

                    {% if result.ep != '' %}
                    <br><b>Entity Page</b>: <a href={{ result.ep }} target='_blank'>{{ result.ep }}</a>
                    {% endif %}
            </div>

            <div>
                <b>Related entities</b>: {{ result.related_entities|length }}<br>
                <p>Label | Dataset | (Related Score) | Entity Search</p>
                <ol>
                    {% for related_entity in result.related_entities %} <!-- |slice:":10" -->
                    {% if forloop.counter <= 10 %}
                    <li style="display:list-item;" class="related_item">
                        {% else %}
                    <li style="display:none;" class="related_item">
                        {% endif %}
                        {% if related_entity.type == 'PER' %}
                        <span class="badge rounded-pill text-white bg-primary">person</span>
                        {% elif related_entity.type == 'LOC' %}
                        <span class="badge rounded-pill text-white bg-info">location</span>
                        {% else %}
                        <span class="badge rounded-pill text-white bg-dark">other</span>
                        {% endif %}
                        <a href="{{related_entity.ep}}">{{ related_entity.name }}</a>
                        ({{ related_entity.score|truncatechars:6 }})
                        <a href="/cm_e_search/search_result/?query={{related_entity.name}}" role="button"
                           alt='Query this entity'><i class="fas fa-search"></i></a>
                    </li>
                    {% endfor %}

                </ol>
                {% if result.related_entities|length > 10 %}

                <button onclick="more_items('related_item')" class="btn btn-secondary btn-sm" type="button" id="more_e"
                        style="display: inline-block; margin: 0 auto;">More
                </button>
                <button onclick="less_items('related_item')" class="btn btn-outline-secondary btn-sm" type="button"
                        id="less_e" style="display: inline-block; margin: 0 auto;">Less
                </button>
                {% endif %}
            </div>
            <br>
            <!-- END RELATED ENTITIES -->

            <hr>

            <!-- BEGIN JOURNAL MENTIONS -->
            <div>
                <b>Occurs in Journals</b>: {{ result.journal_occs|length }}<br>
                <p>(Number of mentions) | Journal | [Oldest mention - Latest mention]</p>
                <ul style="list-style-type: none;">
                    {% for occurrence in result.journal_occs %}

                    {% if forloop.counter < 10 %}
                    <li style="display:list-item;" class="journal">
                        {% else %}
                    <li style="display:none;" class="journal">
                        {% endif %}

                        ({{ occurrence.mentions | length }})
                        <a href="#" onclick="show_journal('{{forloop.counter}}')">{{ occurrence.j_name }}</a>

                        [{{ occurrence.first }} - {{ occurrence.last }}]

                        <div class="mentions mb-3" id="{{forloop.counter}}"
                             style="display: none; overflow-y: scroll; max-height: 400px;">
                            <ul>
                                <ul style="list-style-type: none;">
                                    <li><i>Text</i>: {{ occurrence.mentions.spot }}</li>
                                    <li><i>Date</i>: {{ occurrence.mentions.date }}</li>
                                    <li><i>Position (offset)</i>: {{ occurrence.mentions.start }} -
                                        {{ occurrence.mentions.end }}
                                    </li>
                                    <li><i>Ref. in Visual Library</i>: <a
                                            href="http://sammlungen.ub.uni-frankfurt.de/cm/periodical/pageview/{{ occurrence.mentions.p_link }}">Visual
                                        Library</a></li>
                                </ul>
                            </ul>
                        </div>
                    </li>
                    {% endfor %}
                </ul>

                {% if result.occurrences|length > 10 %}

                <button onclick="more_items('journal')" class="btn btn-secondary btn-sm" type="button" id="more_e"
                        style="display: inline-block; margin: 0 auto;">More
                </button>
                <button onclick="less_items('journal')" class="btn btn-outline-secondary btn-sm" type="button"
                        id="less_e" style="display: inline-block; margin: 0 auto;">Less
                </button>
                {% endif %}

            </div>
            <!-- END JOURNAL MENTIONS -->
            <br>

            {% endfor %}
        </div>


    </div>

    <div class="col-md-0 col-lg-3 col-xl-4">
        <div class="img-fluid sticky-top mt-4" id="picturemargintop30">
            <img src="/static/img/westend-synagoge.webp" class="img-thumbnail img-fluid" alt="Westend Synagogue">
        </div>
    </div>

</main>

{% endblock content %}