labs/api/urls.py
from django.urls import path
from .solrapi import (
    JudaicalinkProxy, CMProxy,
    CMEntitiesProxy, CMEntityNamesProxy, CMMetaProxy
)
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# API endpoints
urlpatterns = [
    path('judaicalink/',        JudaicalinkProxy.as_view(),    name='api-jl'),
    path('cm/',                 CMProxy.as_view(),             name='api-cm'),
    path('cm/entities/',        CMEntitiesProxy.as_view(),      name='api-cm-entities'),
    path('cm/names/',           CMEntityNamesProxy.as_view(),   name='api-cm-entity-names'),
    path('cm/meta/',            CMMetaProxy.as_view(),          name='api-cm-meta'),
]

# Swagger / ReDoc
schema_view = get_schema_view(
    openapi.Info(
        title="Judaicalink Search API",
        default_version='v1',
        description="Solr‐backed search endpoints",
        contact=openapi.Contact(email="info@judaicalink.org"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='api-swagger'),
    path('redoc/',   schema_view.with_ui('redoc',   cache_timeout=0), name='api-redoc'),
]

labs/cm_search/urls.py
from django.urls import path
# for the sitemap
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

from . import views

sitemaps = {'static': StaticViewSitemap}

app_name = 'cm_search'

urlpatterns = [
    path('', views.index, name='cm_search_index'),
    path('search_result/', views.result, name='search_result'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

labs/labs/urls.py
from django.contrib import admin
from django.urls import include, path

from search import views as search_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search.urls', namespace='search')),
    path('', search_views.index, name='index'),
    path('cm_search/', include('cm_search.urls')),
    path('cm_e_search/', include('cm_e_search.urls')),
    path('data/', include('data.urls')),
    #path('captcha/', include('captcha.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


#urlpatterns += [
#    path('captcha/', include('captcha.urls')),
#    ]

handler404 = 'search.views.error_404'
handler500 = 'search.views.error_500'
handler403 = 'search.views.error_403'
handler400 = 'search.views.error_400'

labs/search/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .sitemaps import StaticViewSitemap

# for the sitemap
from django.contrib.sitemaps.views import sitemap

from . import views

sitemaps = {'static': StaticViewSitemap}

app_name = 'search'

urlpatterns = [
    path('index', views.index, name='index'),
    path('all_search_nav', views.all_search_nav, name='all_search_nav'),
    path('search', views.search, name='search'),
    # the sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

labs/search/forms.py
"""
This pages generates the forms for the search.
The forms are generated with crispy forms.
Benjamin Schnabel, 2024
b.schnabel@hs-mannheim.de
"""

from crispy_forms.helper import FormHelper
from django import forms


class SearchForm(forms.Form):
    pass

labs/cm_search/views.py
import logging
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse
import pysolr
import math
from django.conf import settings
from django.views.decorators.cache import cache_page
from django.core.cache.backends.base import DEFAULT_TIMEOUT

logger = logging.getLogger(__name__)
CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)
SOLR_SERVER = settings.SOLR_SERVER
SOLR_INDEX = "cm_meta"


@cache_page(CACHE_TTL)
def index(request):
    return render(request, 'cm_search/search_index.html')


@cache_page(CACHE_TTL)
def result(request):
    error_message = None

    try:

        solr = pysolr.Solr(SOLR_SERVER + SOLR_INDEX, always_commit=True, timeout=10,
                           auth=(settings.SOLR_USER, settings.SOLR_PASSWORD))

        query = request.GET.get('query')
        logger.debug("Query: ", query)
        page = int(request.GET.get('page'))
        size = 10
        # changed size from 15 to 10 to match the amount of results in judaicalink search
        start = (page - 1) * size

        # TODO: add the language, publisher and place to the query and in the index
        highlight_fields = ["page", "text", "dateIssued", "j_title", "vlid_journal", "vlid_page", "volume", "heft",
                            "aufsatz"]
        fields = ["page", "text", "dateIssued", "j_title", "volume", "vlid_journal", "vlid_page", "heft", "aufsatz", "id"]
        search_fields = ["text", "j_title", "aufsatz"]
        # create a dict from the fields and add the query
        # create a list for the fields that should be searched and add the query
        solr_query = [field + ":" + query for field in search_fields]

        # build the body for solr
        body = {
            "hl": "true",
            "indent": "true",
            'fl': ','.join(fields),
            "hl.requireFieldMatch": "true",
            "hl.tag.pre": "<strong>",
            "hl.tag.post": "</strong>",
            "hl.fragsize": "0",
            "start": start,
            "q.op": "OR",
            "hl.fl": ','.join(highlight_fields),
            "rows": size,
            "useParams": ""
        }

        res = solr.search(q=solr_query, search_handler="/select", **body)
        # added 'from': start, to indicate which results should be displayed
        # 'from' is used to tell solr which results to return by index
        # -> if page = 1 then results 0-9 will be displayed
        # -> if page = 2 then results 10-19 and so on

    except Exception as e:
        logger.error("Error: %s", e)
        error_message = "An error occurred while searching. Please try again later."
        context = {
            'error_message': error_message,
            'total_hits': 0,
            'query': "",
        }
        return render(request, 'cm_search/search_result.html', context)


    logger.debug("Hits: ", res.hits)
    logger.debug(res.docs)
    logger.debug("Res: ", res.highlighting)

    if res.hits == 0:
        error_message = "No results found"
        context = {
            'error_message': error_message,
            'total_hits': 0,
            'query': query,
        }
        return render(request, 'cm_search/search_result.html', context)

    results = []

    for doc in res.docs:

        formatted_doc = doc

        # append the prefix of the url to the journal and page
        journal_link = "https://sammlungen.ub.uni-frankfurt.de/cm/periodical/titleinfo/" + ''.join(
            map(str, doc['vlid_journal']))
        page_link = "https://sammlungen.ub.uni-frankfurt.de/cm/periodical/pageview/" + ''.join(
            map(str, doc['vlid_page']))

        formatted_doc['jl'] = journal_link
        formatted_doc['pl'] = page_link

        results.append(formatted_doc)

        # convert all the lists in the formatted_doc to strings
        for key in formatted_doc:
            formatted_doc[key] = ''.join(map(str, formatted_doc[key]))

        # convert all the date in formatted_doc['dateIssued'] to the format dd.mm.yyyy
        formatted_doc['dateIssued'] = datetime.strptime(formatted_doc['dateIssued'], "%Y-%m-%dT%H:%M:%SZ").strftime("%d.%m.%Y")

        # Highlight the search term in the results
        formatted_doc['text'] = res.highlighting[formatted_doc['id']]['text'][0]

        results.append(formatted_doc)

    logger.debug("Doc: ", formatted_doc)



    # paging
    # -> almost copy from jl-search, except some variable-names

    # TODO: refactor paging
    total_hits = res.hits
    pages = math.ceil(total_hits / size)
    # pages containes necessary amount of pages for paging

    paging = []
    # if page = 1 will contain -2, -1, 0, 1, 2, 3, 4

    paging.append(page - 3)
    paging.append(page - 2)
    paging.append(page - 1)
    paging.append(page)
    paging.append(page + 1)
    paging.append(page + 2)
    paging.append(page + 3)

    real_paging = []
    # if page = 1 will contain 1, 2, 3, 4
    # -> non-existing pages are removed

    for number in paging:
        if number > 1 and number < pages:
            real_paging.append(number)

    context = {
        "results": results,
        "total_hits": total_hits,
        "query": query,
        "pages": pages,
        "previous": page - 1,
        "page": page,
        "next": page + 1,
        "paging": real_paging,
        'error_message': error_message,
    }

    return render(request, 'cm_search/search_result.html', context)

labs/cm_search/templates/cm_search/filter.html
<div class="accordion md-accordion" id="accordionEx" role="button" aria-multiselectable="true">

    <!-- Accordion card -->
    <div class="card">

      <!-- Card header -->
      <div class="card-header" role="button" id="headingOne1">
        <a data-toggle="collapse" href="#collapseOne1" aria-expanded="true"
           aria-controls="collapseOne1">
          <h5 class="mb-0">
            <i class="fas fa-angle-down rotate-icon"></i>
            Journal (number)
          </h5>
        </a>
      </div>

      <!-- Card body -->
      <div id="collapseOne1" class="collapse show" role="button" aria-labelledby="headingOne1">
        <div class="card-body">
          <form>
            <!--<div class="form-group">
              <input type="text" class="form-control" id="journal_search" aria-describedby="journal_info" placeholder="journal title">
              <small id="journal_info" class="form-text text-muted">Looking for something specific?</small>
            </div>-->
            <div class="form-check">
              {% for journal_title in journals.checked %}
              <input type="checkbox" class="form-check-input" id="{{journal_title}}" value="{{journal_title}}">
              <label class="form-check-label" for="{{journal_title}}">{{journal_title}}</label>
              {% endfor %}

              {% for journal_title in journals.unchecked %}
              <input type="checkbox" class="form-check-input" id="{{journal_title}}" value="{{journal_title}}">
              <label class="form-check-label" for="{{journal_title}}">{{journal_title}}</label>
              {% endfor %}
            </div>
            <!--<button type="submit" class="btn btn-primary">Submit</button>-->
          </form>
        </div>
      </div>

    </div>
    <!-- Accordion card -->

  <!-- Accordion card -->
    <div class="card">

      <!-- Card header -->
      <div class="card-header" role="button" id="headingTwo2">
        <a data-toggle="collapse" href="#collapseTwo2" aria-expanded="true"
           aria-controls="collapseTwo2">
          <h5 class="mb-0">
            <i class="fas fa-angle-down rotate-icon"></i>
            Language (number)
          </h5>
        </a>
      </div>

      <!-- Card body -->
      <div id="collapseTwo2" class="collapse show" role="button" aria-labelledby="headingTwo2">
        <div class="card-body">
          <form>
            <div class="form-group">
              <input type="text" class="form-control" id="language_search" aria-describedby="language_info" placeholder="language">
              <small id="language_info" class="form-text text-muted">Looking for something specific?</small>
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="language_check1">
              <label class="form-check-label" for="language_check1">Language 1 (number)</label>
            </div>
            <!--<button type="submit" class="btn btn-primary">Submit</button>-->
          </form>
        </div>
      </div>

    </div>
    <!-- Accordion card -->

  <!-- Accordion card -->
    <div class="card">

      <!-- Card header -->
      <div class="card-header" role="button" id="headingThree3">
        <a data-toggle="collapse" href="#collapseThree3" aria-expanded="true"
           aria-controls="collapseThree3">
          <h5 class="mb-0">
            <i class="fas fa-angle-down rotate-icon"></i>
            Date of Issue (number)
          </h5>
        </a>
      </div>

      <!-- Card body -->
      <div id="collapseThree3" class="collapse show" role="button" aria-labelledby="headingThree3">
        <div class="card-body">
          <form>
            <div class="form-group">
              <label for="slider-range">Example Range input</label>
              <div class="selector">
                <div class="price-slider">
                    <div id="slider-range" class="ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content">
                        <!--<div class="ui-slider-range ui-corner-all ui-widget-header"></div>-->
                        <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                        <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                    </div>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <input id="min-price" type="text" class="form-control" placeholder="from" value="">
                </div>
                -
                <div class="col">
                  <input id="max-price" type="text" class="form-control" placeholder="to">
                </div>
              </div>

            </div>
          </form>
        </div>
      </div>

    </div>
    <!-- Accordion card -->



  </div>

labs/cm_search/templates/cm_search/search_form.html
<form method="get" action="{% url 'cm_search:search_result' %}">
    <div class="col-xs-6">
        <input type="hidden" name="page" value="1">
        <div class="input-group">
            <input class="form-control" type="text" name="query" value="" placeholder="Enter your search keyword">
            <div class="input-group-btn">
                <button type="submit" class="btn btn-primary search_button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </div>
</form>

labs/cm_search/templates/cm_search/search_index.html
{% extends 'search/base.html' %}
{% load static %}

{% block meta %}
    <meta name="keywords" content="judaicalink, search, fulltext, access">
    <meta name="description" content="Search our Compact Memory collection containing over 300 Jewish newspapers and journals of the German speaking area of the years 1768–1938 and beyond.">
{% endblock %}

{% block content %}

<!--content-->
<main class="row">
	<div class="col-12 col-sm-12 ml-xl-0 col-md-12 col-lg-9 col-xl-8">
        <h1 class="text-center">Compact Memory <br>Fulltext Search</h1>
        <form method="get" action="/cm_search/search_result/">
            <div class="col-xs-6">
                <input type="hidden" name="page" value="1">
                <div class="input-group">
                    <input class="form-control" type="text" name="query" value="" placeholder="Enter your search keyword">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary search_button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </form>
        <br>
        <p>The Compact Memory collection comprises over 300 Jewish newspapers and journals of the German speaking area of the years 1768–1938 and beyond. These periodicals represent the complete religious, political, social, literary and academic spectrum of the Jewish community and the "Science of Judaism", thus constituting a major source for the research on Judaism in the Modern Age.
        <br><br>
        Through this interface the user can search the digitized version of the whole collection in fulltext mode. Results are shown by relevance and include, in addition to the text snippet, all metadata about the journal and the edition. For most of the journals are also available the links to the original PDF document of the collection, hosted by the Universitätsbibliothek Frankfurt.
        </p>
    </div>

    <div class="col-md-0 col-lg-3 col-xl-4">
        <div class="alert alert-info text-center mt-4 sticky-top" id="picturemargintop30" role="alert">
            <b>Try some search keywords:</b>
            <ul class="list-unstyled">
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Martin+Buber">Martin Buber</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Franz+Rosenzweig">Franz Rosenzweig</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Einstein">Einstein</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Jerusalem">Jerusalem</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Wissenschaft+des+Judentums">Wissenschaft des Judentums</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Geschichte+der+Juden+in+Deutschland">Geschichte der Juden in Deutschland</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Tel-Aviv">Tel-Aviv</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Zionistenkongress">Zionistenkongress</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=09-11-1939">09-11-1939</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=Oppenheimer">Oppenheimer</a></li>
                <li><i class="fa fa-search-plus"></i> <a href="{url 'cm_search:result'}/?page=1&query=1930">1930</a></li>
            </ul>
        </div>
    </div>
</main>
<!--content end-->

{% endblock content %}

labs/cm_search/templates/cm_search/search_result.html
{% extends 'search/base.html' %}
{% load static %}

{% block content %}

<main class="row">

<div class="col-12 col-sm-12 ml-xl-0 col-md-12 col-lg-9 col-xl-8">

<h1 class="text-center">Compact Memory <br> Fulltext Search</h1>

    <form method="get" action="/cm_search/search_result/">
            <div class="col-xs-6">
                <input type="hidden" name="page" value="1">
                <div class="input-group">
                    <input class="form-control" type="text" name="query" value="{{query}}" placeholder="Enter your search keyword">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary search_button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </form>

    <br>

    {% if total_hits > 0 %}
    <div class="alert alert-success text-center" role="alert">
        Found {{ total_hits }} document(s) for the query "<b>{{ query }}</b>".
    </div>
    {% else %}
    <div class="alert alert-danger text-center" role="alert">
        No documents matching your query "<b>{{ query }}</b>"!
    </div>
    {% endif %}

    <div class="table-responsive">
    <table class="table table-light table-striped">

    {% for result in results %}
        <tr>
            <td class="p-3">
                <b>Matching text</b>: <br>
                    {% if result.text|wordcount > 56 %}
                        <div class="half-content" id="half-{{forloop.counter}}">{{result.text|safe|linebreaks|truncatewords:50}}<br>
                            <button type="button" data-id="{{forloop.counter}}" onclick="javascript:void(0)" class="show-hide-btn btn btn-primary btn-sm mb-2">Read more ></button>
                        </div>
                        <div class="full-content" id="full-{{forloop.counter}}" style="display: none;">{{ result.text|safe|linebreaks }}
                            <button data-id="{{forloop.counter}}" onclick="javascript:void(0)" class="show-hide-btn btn btn-primary btn-sm mb-2">< Read less</button>
                        </div>
                    {% else %}
                        <div>
                            {{ result.text|safe|linebreaks }}
                        </div>
                    {% endif %}

                <div class="pt-1">
                    <b>Journal:</b>
                    {% if result.jl != '' %}
                    <a href={{result.jl}} target="_blank" rel="noopener noreferrer">{{result.j_title|safe}}</a><br>
                    {% else %}
                    {{result.j_title|safe}}
                    {% endif %}

                    {% if result.lang != '' %}
                    <b>Language:</b> {{result.lang|safe}}<br>
                    {% endif %}

                    {% if result.dateIssued != '' %}
                    <b>Date of Issue:</b> {{result.dateIssued|safe}}
                    <br>
                    {% endif %}

                    {% if result.place != '' %}
                    <b>Place:</b> {{result.place|safe}}
                    <br>
                    {% endif %}

                    {% if result.publisher != '' %}
                    <b>Publisher:</b> {{result.publisher|safe}}
                    <br>
                    {% endif %}

                    <b>Bibliographic reference</b><br>

                    {% if result.volume != '' %}
                    &nbsp; Volume: {{result.volume|safe}}<br>
                    {% endif %}

                    {% if result.heft != '' %}
                    &nbsp; Issue: {{result.heft|safe }}<br>
                    {% endif %}

                    {% if result.aufsatz != '' %}
                    &nbsp; Essay: {{result.aufsatz|safe}}<br>
                    {% endif %}

                    {% if result.page != '' and result.page != 'None' %}
                    {% if result.pl != '' %}
                    <b>Page:</b> <a href={{result.pl|safe}} target="_blank" rel="noopener noreferrer">{{result.page|safe}}</a>
                    {% else %}
                    <b>Page:</b> {{result.page|safe}} (Link to the page not available for this journal)
                    {% endif %}
                    {% endif %}
                </div>

            </td>

        </tr>

    {% endfor %}

    </table>
    </div>
    <br> <br>

        <!-- paging -->

    {% if pages > 1 %}

        <form style="display: inline;" method="get" action="/cm_search/search_result/">
            <input type="hidden" name="query" value="{{ query }}">
            <input type="hidden" name="page" value="{{ 1 }}">
            {% if page != 1 %}
            <button class="paging_button_inactive" type="submit" > {{ 1 }} </button>
            {% else %}
            <button class="paging_button_active" type="submit" > {{ 1 }} </button>
            {% endif %}
        </form>

        {% if page != 1 %}

        <form style="display: inline;" method="get" action="/cm_search/search_result/">
            <input type="hidden" name="query" value="{{ query }}">
            <input type="hidden" name="page" value="{{ previous }}">
            <button class="paging_button_inactive" type="submit" > previous </button>
        </form>

    {% endif %}

    {% for i in paging %}

            <form style="display: inline;" method="get" action="/cm_search/search_result/">
                <input type="hidden" name="query" value="{{ query }}">
                <input type="hidden" name="page" value="{{ i }}">
                {% if i == page %}
                <button class="paging_button_active" type="submit" > {{ i }} </button>
                {% else %}
                <button class="paging_button_inactive" type="submit" > {{ i }} </button>
                {% endif %}
            </form>

    {% endfor %}

    {% if page != pages %}

        <form style="display: inline;" method="get" action="/cm_search/search_result/">
            <input type="hidden" name="query" value="{{ query }}">
            <input type="hidden" name="page" value="{{ next }}">
            <button class="paging_button_inactive" type="submit" > next </button>
        </form>

    {% endif %}

        {% if pages != 1 %}

        <form style="display: inline;" method="get" action="/cm_search/search_result/">
            <input type="hidden" name="query" value="{{ query }}">
            <input type="hidden" name="page" value="{{ pages }}">
            {% if page != pages %}
            <button class="paging_button_inactive" type="submit" > {{ pages }} </button>
            {% else %}
            <button class="paging_button_active" type="submit" > {{ pages }} </button>
            {% endif %}
        </form>

        {% endif %}

    {% endif %}


</div>
    <div class="col-md-0 col-lg-3 col-xl-4">
            <div class="img-fluid sticky-top mt-4" id="picturemargintop30">
            <img src="/static/img/books.webp" class="img-thumbnail img-fluid" alt="stack of newspapers">
            </div>
    </div>
</main>

{% endblock content %}